/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gymapp;

import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author fess
 */
public class Gym extends javax.swing.JFrame {

    /**
     * Creates new form Gym
     */
    public Gym() {
        initComponents();
        ConsoleWriter.getInstance().setJTextArea(jConsoleTextArea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAddClient = new javax.swing.JButton();
        jButtonRemoveClient = new javax.swing.JButton();
        jButtonShowAllClients = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonAddTrainer = new javax.swing.JButton();
        jButtonRemoveTrainer = new javax.swing.JButton();
        jButtonShowAllTrainers = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonShowReport = new javax.swing.JButton();
        jTextFieldFrom = new javax.swing.JTextField();
        jTextFieldTo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButtonAddTables = new javax.swing.JButton();
        jButtonRemoveAllTables = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jConsoleTextArea = new javax.swing.JTextArea();
        jButtonQuery = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gym");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Клієнти"));

        jButtonAddClient.setText("Додати клієнта");
        jButtonAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddClientActionPerformed(evt);
            }
        });

        jButtonRemoveClient.setText("Видалити клієнта ");
        jButtonRemoveClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveClientActionPerformed(evt);
            }
        });

        jButtonShowAllClients.setText("Облік клієнтів");
        jButtonShowAllClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllClientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonRemoveClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAddClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonShowAllClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonAddClient)
                .addGap(4, 4, 4)
                .addComponent(jButtonRemoveClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonShowAllClients)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Тренери"));

        jButtonAddTrainer.setText("Додати тренера");
        jButtonAddTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTrainerActionPerformed(evt);
            }
        });

        jButtonRemoveTrainer.setText("Видалити тренера ");
        jButtonRemoveTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveTrainerActionPerformed(evt);
            }
        });

        jButtonShowAllTrainers.setText("Облік тренерів");
        jButtonShowAllTrainers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllTrainersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonRemoveTrainer, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
            .addComponent(jButtonAddTrainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonShowAllTrainers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButtonAddTrainer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRemoveTrainer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonShowAllTrainers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Оплата"));

        jButtonShowReport.setText("Облік оплати");
        jButtonShowReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowReportActionPerformed(evt);
            }
        });

        jTextFieldFrom.setToolTipText("от");

        jTextFieldTo.setToolTipText("до");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonShowReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldFrom)
            .addComponent(jTextFieldTo)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jTextFieldFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonShowReport))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Робота з БД"));

        jButtonAddTables.setText("Додати таблиці до БД");
        jButtonAddTables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTablesActionPerformed(evt);
            }
        });

        jButtonRemoveAllTables.setText("Видалити таблиці з БД");
        jButtonRemoveAllTables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveAllTablesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonAddTables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonRemoveAllTables, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButtonAddTables)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRemoveAllTables))
        );

        jConsoleTextArea.setEditable(false);
        jConsoleTextArea.setColumns(20);
        jConsoleTextArea.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jConsoleTextArea.setRows(5);
        jScrollPane1.setViewportView(jConsoleTextArea);

        jButtonQuery.setText("Виконати запит");
        jButtonQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQueryActionPerformed(evt);
            }
        });

        jButtonClear.setText("Очистить");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClear))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jButtonQuery)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddTablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTablesActionPerformed
        DBManager dbManager = new DBManager();
        try {
            dbManager.createTables();
            ConsoleWriter.getInstance().write("Tables created successfully.");
        } catch (SQLException ex) {
            ConsoleWriter.getInstance().write(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButtonAddTablesActionPerformed

    private void jButtonRemoveAllTablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveAllTablesActionPerformed
        DBManager dbManager = new DBManager();
        try {
            dbManager.deleteTables();
            ConsoleWriter.getInstance().write("Tables deleted successfully.");
        } catch (SQLException ex) {
            ConsoleWriter.getInstance().write(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButtonRemoveAllTablesActionPerformed

    private void jButtonAddTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTrainerActionPerformed
        Trainers trainers = new Trainers();
        try {
            trainers.addTrainer();
            ConsoleWriter.getInstance().write("Trainers inserted successfully.");
        } catch (SQLException ex) {
            ConsoleWriter.getInstance().write(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButtonAddTrainerActionPerformed

    private void jButtonRemoveTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveTrainerActionPerformed
        Trainers trainers = new Trainers();
        try {
            trainers.removeTrainer();
            ConsoleWriter.getInstance().write("Trainer removed successfully.");
        } catch (SQLException ex) {
            ConsoleWriter.getInstance().write(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButtonRemoveTrainerActionPerformed

    private void jButtonShowAllTrainersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllTrainersActionPerformed
        Trainers trainers = new Trainers();
        try {
            trainers.showTrainers();
        } catch (SQLException ex) {
            ConsoleWriter.getInstance().write(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButtonShowAllTrainersActionPerformed

    private void jButtonAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddClientActionPerformed
        Clients clients = new Clients();
        try {
            clients.addClient();
            ConsoleWriter.getInstance().write("Clients inserted successfully.");
        } catch (SQLException ex) {
            ConsoleWriter.getInstance().write(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButtonAddClientActionPerformed

    private void jButtonRemoveClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveClientActionPerformed
        Clients clients = new Clients();
        try {
            clients.removeClient();
            ConsoleWriter.getInstance().write("Client removed successfully.");
        } catch (SQLException ex) {
            ConsoleWriter.getInstance().write(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButtonRemoveClientActionPerformed

    private void jButtonShowAllClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllClientsActionPerformed
        Clients clients = new Clients();
        try {
            clients.showClients();
        } catch (SQLException ex) {
            ConsoleWriter.getInstance().write(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButtonShowAllClientsActionPerformed

    private void jButtonShowReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowReportActionPerformed
        Date dateFrom = new Date(0);
        Date dateTo = new Date(System.currentTimeMillis());
        
        try {
            dateFrom = Date.valueOf(jTextFieldFrom.getText());
            dateTo = Date.valueOf(jTextFieldTo.getText());
        } catch (IllegalArgumentException ex) {
            ConsoleWriter.getInstance().write("Wrong date format.");
        }
        
        Reports reports = new Reports();
        try {
            reports.filterData(dateFrom, dateTo);
        } catch (SQLException ex) {
            ConsoleWriter.getInstance().write(ex.getLocalizedMessage());
        } catch (ParseException ex) {
            ConsoleWriter.getInstance().write(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButtonShowReportActionPerformed

    private void jButtonQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQueryActionPerformed
        CommandFrame frame = new CommandFrame();
        frame.setDefaultCloseOperation (JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setVisible (true);
    }//GEN-LAST:event_jButtonQueryActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        ConsoleWriter.getInstance().clear();
    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gym().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddClient;
    private javax.swing.JButton jButtonAddTables;
    private javax.swing.JButton jButtonAddTrainer;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonQuery;
    private javax.swing.JButton jButtonRemoveAllTables;
    private javax.swing.JButton jButtonRemoveClient;
    private javax.swing.JButton jButtonRemoveTrainer;
    private javax.swing.JButton jButtonShowAllClients;
    private javax.swing.JButton jButtonShowAllTrainers;
    private javax.swing.JButton jButtonShowReport;
    private javax.swing.JTextArea jConsoleTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldFrom;
    private javax.swing.JTextField jTextFieldTo;
    // End of variables declaration//GEN-END:variables
}
